### ISSUE TITLE
Error must prompt when trying to uninstall/delete the program while service is running

### ISSUE THREAD

**Issue by 133122** [BV5Tl0N/TheDupe#3]
**Is your feature request related to a problem? Please describe.**
No error prompted when trying to remove the program when service is running

**Describe the solution you'd like**
Should have error when performing the deletion action while service is running.

**Comment by BV5Tl0N** [comment]
Won't fix, there is a step that forcibly closes tasks related to The Dupe. This will be in conflict with that.
