### ISSUE TITLE
Must delete all the of files in the folder once program uninstalled

### ISSUE THREAD

**Issue by 133122** [BV5Tl0N/TheDupe#4]
**Is your feature request related to a problem? Please describe.**
Config file and two svc files retained after uninstalling the application.

**Comment by BV5Tl0N** [comment]
Acknowledging this issue, will fix on the next release.

**Comment by BV5Tl0N** [comment]
Added step to forcibly close running application so all files will be deleted during uninstallation. This fix will be released on the next version.
