### ISSUE TITLE
The Dupe Service should not run if log_dir value is invalid

### ISSUE THREAD

**Issue by 4S7R4L** [BV5Tl0N/TheDupe#5]
When changing the value of log_dir invalid (e.g. not a folder path), the dupe service still runs. Now I don't know where would the logs of the dupe will go. If the log_dir value is invalid, the dupe service should not run.

**Comment by BV5Tl0N** [comment]
Acknowledging this issue, will fix on the next release.

**Comment by BV5Tl0N** [comment]
If log_dir is set to invalid path, it will use default paths.
